log:
    level: debug 

entryPoints:
    http:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true

    https:
        address: ":443"
        http:
            tls: {}
    
    mysql:
        address: ":3306"
    
    postgres:
        address: ":5432"

api:
    insecure: true
    
providers:
    docker:
        exposedByDefault: false
    file:
        directory: /etc/traefik/conf.d
