log:
    level: debug 

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true

    websecure:
        address: ":443"
        http:
            tls: {}
api:
    insecure: true
    
providers:
    docker:
        exposedByDefault: false
    file:
        directory: /etc/traefik/conf.d
